# fastra_core\knowledge\domains\material\auto_generated.py

from __future__ import annotations

import logging
from typing import Any, Dict, List
from pydantic import BaseModel, ConfigDict, Field

from fastra_core.knowledge.graph import KnowledgeGraph
from fastra_core.knowledge.nodes import MaterialNode

logger = logging.getLogger("fastra.knowledge")


# ---------------------------------------------------------------------------
# Inbound DTOs – Pydantic Strict Gateway & Sanitization (Fail-Fast)
# ---------------------------------------------------------------------------

class AutoGeneratedMaterialItemDTO(BaseModel):
    """DTO validasi ketat untuk mendaftar data material cetakan generator otomatis."""
    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True, strict=False)

    id: str = Field(..., min_length=5, max_length=64, pattern=r"^mat_[a-z0-9_\\.\\-]+$")
    name: str = Field(..., min_length=2, max_length=256)
    unit: str = Field(..., min_length=1, max_length=16, pattern=r"^[A-Za-z0-9²³\/()\s\u00B3]+$")
    category: str = Field(default="", max_length=128)
    specifications: Dict[str, Any] = Field(default_factory=dict, max_length=100)
    volatility_factor: float = Field(default=0.0, ge=0.0, le=1.0, allow_inf_nan=False)


class AutoGeneratedMaterialBundleDTO(BaseModel):
    """Bundel manifes penampung sekumpulan daftar material generator otomatis."""
    model_config = ConfigDict(extra="forbid", strict=False)
    items: List[AutoGeneratedMaterialItemDTO] = Field(default_factory=list, max_length=1000)


# ---------------------------------------------------------------------------
# Core Utilities & Automated Seeding Generator Layer
# ---------------------------------------------------------------------------

def load_material_auto_generated(kg: KnowledgeGraph) -> None:
    """
    Memuat dan menginjeksikan data spesifikasi master material dasar pelengkap relasi.
    Menghilangkan loop argument dinamis unsafe pointer references (*args) melalui pemetaan eksplisit.
    """
    if not isinstance(kg, KnowledgeGraph):
        raise TypeError("Parameter masukan 'kg' wajib berupa instance orisinil dari kelas KnowledgeGraph.")

    # Kumpulan data benih material dasar terstandarisasi untuk pemenuhan analisis komparatif (AHS PUPR)
    raw_bundle_payload: List[Dict[str, Any]] = [
        {
            "id": "mat_semen_portland",
            "name": "Semen Portland (PC) PC-40",
            "unit": "kg",
            "category": "SEMEN",
            "specifications": {"tipe": "PC-40", "harga_patokan": 1400.0},
            "volatility_factor": 0.05
        },
        {
            "id": "mat_pasir_pasang",
            "name": "Pasir Pasang Cor / Beton Luar",
            "unit": "m³",
            "category": "AGREGAT_KASAR",
            "specifications": {"tipe": "Pasir Cor", "harga_patokan": 290000.0},
            "volatility_factor": 0.08
        },
        {
            "id": "mat_bata_merah",
            "name": "Bata Merah Konstruksi Standar",
            "unit": "buah",
            "category": "MASONRY",
            "specifications": {"tipe": "Bata Merah Lokal", "harga_patokan": 950.0},
            "volatility_factor": 0.03
        },
        {
            "id": "mat_baja_tulangan",
            "name": "Besi Baja Tulangan Beton U-24 Polos",
            "unit": "kg",
            "category": "BESI_BAJA",
            "specifications": {"grade": "U-24", "harga_patokan": 13500.0},
            "volatility_factor": 0.12
        }
    ]

    # 1. GATEWAY SCHEMA VALIDATION: Penyaringan fail-fast terpusat
    try:
        validated_bundle = AutoGeneratedMaterialBundleDTO(items=raw_bundle_payload)
    except Exception as exc:
        logger.error(f"Gagal memuat benih material otomatis: Kegagalan skema data: {str(exc)}")
        return

    # 2. IMMUTABLE OBJECT CONSTRUCTOR MAPPING PIPELINE
    for item_dto in validated_bundle.items:
        # Instansiasi objek dipaksa melalui kelas murni MaterialNode bernama eksplisit demi mematikan bug memori pointer
        material_node_instance = MaterialNode(
            id=item_dto.id,
            name=item_dto.name,
            unit=item_dto.unit,
            category=item_dto.category,
            specifications=item_dto.specifications,
            volatility_factor=item_dto.volatility_factor
        )
        kg.add_material(material_node_instance)

    logger.info(
        "Daftar material pelengkap otomatis sukses disuntikkan ke repositori utama: %d master nodes terkunci.",
        len(validated_bundle.items)
    )
