"""Domain WorkItem: Auto-generated untuk Relasi SNI"""
def load_wi_auto_generated(kg):
    from fastra_core.knowledge.nodes import WorkItemNode
    items = [
        ("wi-acian", "WI.ACIAN", "Acian", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-atap-baja-ringan", "WI.ATAP.BA", "Atap Baja Ringan", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-bak-kontrol", "WI.BAK.KON", "Bak Kontrol", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-batu-belah-1-5", "WI.BATU.BE", "Batu Belah 1 5", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-batu-koral", "WI.BATU.KO", "Batu Koral", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-bekisting-balok", "WI.BEKISTI", "Bekisting Balok", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-bekisting-kolom", "WI.BEKISTI", "Bekisting Kolom", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-besi-ulir", "WI.BESI.UL", "Besi Ulir", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-beton-abutment", "WI.BETON.A", "Beton Abutment", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-beton-k225", "WI.BETON.K", "Beton K225", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-beton-k250", "WI.BETON.K", "Beton K250", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-bore-pile-jembatan", "WI.BORE.PI", "Bore Pile Jembatan", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-bronjong", "WI.BRONJON", "Bronjong", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-bronjong-kawat", "WI.BRONJON", "Bronjong Kawat", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-cat-anti-karat", "WI.CAT.ANT", "Cat Anti Karat", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-cat-besi", "WI.CAT.BES", "Cat Besi", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-cat-eksterior", "WI.CAT.EKS", "Cat Eksterior", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-cat-kayu", "WI.CAT.KAY", "Cat Kayu", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-cat-tembok", "WI.CAT.TEM", "Cat Tembok", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-diffuser-ac", "WI.DIFFUSE", "Diffuser Ac", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-elastomeric-bearing", "WI.ELASTOM", "Elastomeric Bearing", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-exhaust-fan-10in", "WI.EXHAUST", "Exhaust Fan 10In", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-galian-tanah", "WI.GALIAN.", "Galian Tanah", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-ganti-keramik", "WI.GANTI.K", "Ganti Keramik", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-genteng-beton", "WI.GENTENG", "Genteng Beton", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-genteng-metal", "WI.GENTENG", "Genteng Metal", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-gorong-gorong", "WI.GORONG.", "Gorong Gorong", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-granit-lantai", "WI.GRANIT.", "Granit Lantai", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-grouting-beton", "WI.GROUTIN", "Grouting Beton", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-guardrail", "WI.GUARDRA", "Guardrail", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-instalasi-access-point", "WI.INSTALA", "Instalasi Access Point", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-instalasi-alarm", "WI.INSTALA", "Instalasi Alarm", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-instalasi-cctv", "WI.INSTALA", "Instalasi Cctv", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-instalasi-detector", "WI.INSTALA", "Instalasi Detector", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-instalasi-emergency-light", "WI.INSTALA", "Instalasi Emergency Light", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-instalasi-hydrant", "WI.INSTALA", "Instalasi Hydrant", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-instalasi-nvr", "WI.INSTALA", "Instalasi Nvr", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-instalasi-panel", "WI.INSTALA", "Instalasi Panel", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-instalasi-sensor-gas", "WI.INSTALA", "Instalasi Sensor Gas", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-instalasi-sprinkler", "WI.INSTALA", "Instalasi Sprinkler", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-instalasi-stop-kontak", "WI.INSTALA", "Instalasi Stop Kontak", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-instalasi-titik-lampu", "WI.INSTALA", "Instalasi Titik Lampu", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-jacketing-kolom", "WI.JACKETI", "Jacketing Kolom", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-jendela-kayu", "WI.JENDELA", "Jendela Kayu", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-kanopi", "WI.KANOPI", "Kanopi", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-keramik-dinding", "WI.KERAMIK", "Keramik Dinding", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-keramik-lantai", "WI.KERAMIK", "Keramik Lantai", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-kusen-kayu", "WI.KUSEN.K", "Kusen Kayu", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-lantai-spc", "WI.LANTAI.", "Lantai Spc", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-nok-genteng", "WI.NOK.GEN", "Nok Genteng", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-pagar-besi", "WI.PAGAR.B", "Pagar Besi", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-pagar-brc", "WI.PAGAR.B", "Pagar Brc", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-pas-bata", "WI.PAS.BAT", "Pas Bata", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-pas-bata-ringan", "WI.PAS.BAT", "Pas Bata Ringan", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-pasang-ac-1pk", "WI.PASANG.", "Pasang Ac 1Pk", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-pasang-ac-2pk", "WI.PASANG.", "Pasang Ac 2Pk", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-pasang-apar", "WI.PASANG.", "Pasang Apar", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-pasang-bollard", "WI.PASANG.", "Pasang Bollard", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-pasang-ducting-ac", "WI.PASANG.", "Pasang Ducting Ac", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-pasang-kaca-tempered", "WI.PASANG.", "Pasang Kaca Tempered", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-pasang-karpet-tile", "WI.PASANG.", "Pasang Karpet Tile", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-pasang-kitchen-set", "WI.PASANG.", "Pasang Kitchen Set", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-pasang-kloset", "WI.PASANG.", "Pasang Kloset", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-pasang-lantai-spc", "WI.PASANG.", "Pasang Lantai Spc", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-pasang-partisi-aluminium", "WI.PASANG.", "Pasang Partisi Aluminium", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-pasang-rambu", "WI.PASANG.", "Pasang Rambu", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-pasang-septic-tank", "WI.PASANG.", "Pasang Septic Tank", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-pasang-wastafel", "WI.PASANG.", "Pasang Wastafel", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-pasang-water-heater", "WI.PASANG.", "Pasang Water Heater", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-pc-girder-erection", "WI.PC.GIRD", "Pc Girder Erection", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-perbaikan-atap-bocor", "WI.PERBAIK", "Perbaikan Atap Bocor", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-perbaikan-beton-retak", "WI.PERBAIK", "Perbaikan Beton Retak", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-perbaikan-instalasi-listrik", "WI.PERBAIK", "Perbaikan Instalasi Listrik", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-perbaikan-plafon", "WI.PERBAIK", "Perbaikan Plafon", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-pintu-panel", "WI.PINTU.P", "Pintu Panel", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-pipa-air-bersih-1-2", "WI.PIPA.AI", "Pipa Air Bersih 1 2", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-pipa-air-kotor-4", "WI.PIPA.AI", "Pipa Air Kotor 4", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-pipa-drainase", "WI.PIPA.DR", "Pipa Drainase", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-plafon-gypsum", "WI.PLAFON.", "Plafon Gypsum", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-plafon-tripleks", "WI.PLAFON.", "Plafon Tripleks", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-plesteran", "WI.PLESTER", "Plesteran", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-pondasi-batu", "WI.PONDASI", "Pondasi Batu", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-saluran-drainase", "WI.SALURAN", "Saluran Drainase", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-sumur-resapan", "WI.SUMUR.R", "Sumur Resapan", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-talud-batu", "WI.TALUD.B", "Talud Batu", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-taman-rumput", "WI.TAMAN.R", "Taman Rumput", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-tanam-pohon", "WI.TANAM.P", "Tanam Pohon", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-tiang-pancang-jembatan", "WI.TIANG.P", "Tiang Pancang Jembatan", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-turap-batu-kali", "WI.TURAP.B", "Turap Batu Kali", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-urugan-pasir", "WI.URUGAN.", "Urugan Pasir", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-urugan-tanah", "WI.URUGAN.", "Urugan Tanah", "unit", "AHSP PUPR", "TAMBAHAN"),
        ("wi-waterproofing-coating-ulang", "WI.WATERPR", "Waterproofing Coating Ulang", "unit", "AHSP PUPR", "TAMBAHAN"),
    ]
    for args in items:
        kg.add_work_item(WorkItemNode(*args))
    print(f"  ✅ Auto-Generated: {len(items)} item pekerjaan dimuat")