"""Domain Work Item: Dinding, Kusen & Arsitektur Kulit Luar - Kelompok V"""
def load_wi_dinding_kusen(kg):
    from fastra_core.knowledge.nodes import WorkItemNode
    items = [
        ("wi-hebel-lt1", "DIN.001", "Pemasangan Dinding Bata Ringan (Hebel) Tebal 10 cm Lantai 1", "m²", "AHSP PUPR", "DINDING"),
        ("wi-thinbed-hebel", "DIN.002", "Penggunaan Semen Mortar Perekat Bata Ringan (Thinbed)", "m²", "AHSP PUPR", "DINDING"),
        ("wi-hebel-trasram", "DIN.003", "Pemasangan Dinding Hebel Transram (Kedap Air) Area Kamar Mandi", "m²", "AHSP PUPR", "DINDING"),
        ("wi-hebel-lt2", "DIN.004", "Pemasangan Dinding Bata Ringan (Hebel) Tebal 10 cm Lantai 2", "m²", "AHSP PUPR", "DINDING"),
        ("wi-bata-merah-taman", "DIN.005", "Pemasangan Pasangan Bata Merah untuk Area Bak Kontrol/Taman", "m²", "AHSP PUPR", "DINDING"),
        ("wi-kepalaan-plester", "DIN.006", "Pembuatan Lajur Panduan Tebal Plesteran Dinding (Kepalaan Plester)", "m²", "AHSP PUPR", "DINDING"),
        ("wi-kawat-ayam", "DIN.007", "Pemasangan Kawat Ayam Perlindungan Retak Pertemuan Hebel-Beton", "m'", "AHSP PUPR", "DINDING"),
        ("wi-plester-dalam", "DIN.008", "Pekerjaan Plesteran Dinding Hebel Dalam Ruangan Campuran Mortar", "m²", "SNI 6897", "DINDING"),
        ("wi-plester-luar", "DIN.009", "Pekerjaan Plesteran Dinding Hebel Luar Ruangan (Tahan Cuaca)", "m²", "SNI 6897", "DINDING"),
        ("wi-plester-kasar-km", "DIN.010", "Pekerjaan Plesteran Kamar Mandi Kasar sebagai Dudukan Keramik", "m²", "AHSP PUPR", "DINDING"),
        ("wi-acian-dalam", "DIN.011", "Pekerjaan Acian Halus Dinding Plesteran Dalam Ruangan", "m²", "SNI 6897", "DINDING"),
        ("wi-acian-luar", "DIN.012", "Pekerjaan Acian Halus Dinding Plesteran Luar Ruangan", "m²", "SNI 6897", "DINDING"),
        ("wi-amplas-acian", "DIN.013", "Pekerjaan Pengampelasan Permukaan Dinding Acian hingga Mulus", "m²", "AHSP PUPR", "DINDING"),
        ("wi-tali-air", "DIN.014", "Pembuatan Detail Garis Celah Dekoratif Luar (Tali Air Minimalis)", "m'", "AHSP PUPR", "DINDING"),
        ("wi-corner-bead", "DIN.015", "Pemasangan Profil Sudut PVC (Corner Bead) pada Siku Dinding", "m'", "AHSP PUPR", "DINDING"),
        ("wi-kusen-pintu-utama", "DIN.016", "Pemasangan Kusen Pintu Utama Bahan Kayu Jati Oven Finishing Melamik", "unit", "SNI 3434", "KUSEN"),
        ("wi-kusen-jendela-aluminium", "DIN.017", "Pemasangan Kusen Jendela Rangka Aluminium 4 Inci Powder Coating White", "unit", "AHSP PUPR", "KUSEN"),
        ("wi-kusen-pintu-kamar", "DIN.018", "Pemasangan Kusen Pintu Kamar Tidur Rangka Aluminium 3 Inci", "unit", "AHSP PUPR", "KUSEN"),
        ("wi-dynabolt-kusen", "DIN.019", "Pemasangan Sekrup Dynabolt Pengikat Kusen Aluminium ke Dinding", "titik", "AHSP PUPR", "KUSEN"),
        ("wi-foam-kusen", "DIN.020", "Penyemprotan Cairan Polyurethane Foam Sela Kusen & Dinding", "unit", "AHSP PUPR", "KUSEN"),
        ("wi-daun-pintu-utama", "DIN.021", "Pemasangan Daun Pintu Utama Bahan Kayu Jati Solid Custom", "unit", "SNI 3434", "KUSEN"),
        ("wi-daun-pintu-kamar", "DIN.022", "Pemasangan Daun Pintu Kamar Tidur Bahan Engineered Wood (HDF)", "unit", "SNI 3434", "KUSEN"),
        ("wi-jendela-casement", "DIN.023", "Pemasangan Daun Jendela Aluminium Model Ayun (Casement)", "unit", "AHSP PUPR", "KUSEN"),
        ("wi-jendela-sliding", "DIN.024", "Pemasangan Daun Jendela Aluminium Model Geser (Sliding)", "unit", "AHSP PUPR", "KUSEN"),
        ("wi-kaca-polos-5mm", "DIN.025", "Pemasangan Kaca Polos Tebal 5mm pada Daun Jendela Kamar", "m²", "SNI 15-0047", "KUSEN"),
        ("wi-kaca-sanblast", "DIN.026", "Pemasangan Kaca Sanblast Buram Tebal 5mm Kamar Mandi", "m²", "SNI 15-0047", "KUSEN"),
        ("wi-karet-sealant-kaca", "DIN.027", "Pemasangan Karet Sealant Kaca pada Rangka Daun Jendela", "m'", "AHSP PUPR", "KUSEN"),
        ("wi-engsel-pintu", "DIN.028", "Pemasangan Engsel Kupu-Kupu Stainless Steel 4 Inci Pintu Utama", "set", "SNI 3434", "KUSEN"),
        ("wi-engsel-jendela", "DIN.029", "Pemasangan Engsel Jendela Aluminium Model Friction Stay", "set", "AHSP PUPR", "KUSEN"),
        ("wi-mortise-lock", "DIN.030", "Pemasangan Rumah Kunci Pintu Utama Sistem Mortise Lock Heavy Duty", "set", "SNI 3434", "KUSEN"),
        ("wi-handle-pintu", "DIN.031", "Pemasangan Gagang Pintu (Handle) Stainless Steel Pintu Utama", "buah", "SNI 3434", "KUSEN"),
        ("wi-kunci-km", "DIN.032", "Pemasangan Kunci Bulat Kamar Mandi Bahan Kuningan Anti Karat", "buah", "AHSP PUPR", "KUSEN"),
        ("wi-flush-bolt", "DIN.033", "Pemasangan Grendel Tanam (Flush Bolt) pada Daun Pintu Ganda", "buah", "AHSP PUPR", "KUSEN"),
        ("wi-door-closer", "DIN.034", "Pemasangan Alat Penutup Pintu Otomatis (Door Closer) Hidrolik", "unit", "AHSP PUPR", "KUSEN"),
        ("wi-door-stop", "DIN.035", "Pemasangan Penahan Pintu Magnetis (Door Stop) Tanam Lantai", "buah", "AHSP PUPR", "KUSEN"),
        ("wi-waterproofing-km1", "DIN.036", "Pelapisan Semen Anti Bocor (Waterproofing Slurry) Lantai Kamar Mandi 1", "m²", "AHSP PUPR", "DINDING"),
        ("wi-waterproofing-km2", "DIN.037", "Pelapisan Semen Anti Bocor (Waterproofing Slurry) Lantai Kamar Mandi 2", "m²", "AHSP PUPR", "DINDING"),
        ("wi-waterproofing-balkon", "DIN.038", "Pelapisan Semen Anti Bocor (Waterproofing Membran) Area Balkon Atas", "m²", "AHSP PUPR", "DINDING"),
        ("wi-batu-alam-fasad", "DIN.039", "Pemasangan Dinding Fasad Luar Bahan Batu Alam Andesit Bakar", "m²", "AHSP PUPR", "FASAD"),
        ("wi-batu-alam-sirih", "DIN.040", "Pemasangan Batu Alam Tempel Pola Susun Sirih Dinding Depan", "m²", "AHSP PUPR", "FASAD"),
        ("wi-coating-batu-alam", "DIN.041", "Pengolesan Cairan Pelindung Batu Alam (Coating Matte/Glossy)", "m²", "AHSP PUPR", "FASAD"),
        ("wi-acp-panel", "DIN.042", "Pemasangan Dinding Fasad Bahan ACP (Aluminium Composite Panel)", "m²", "AHSP PUPR", "FASAD"),
        ("wi-rangka-acp", "DIN.043", "Pembuatan Rangka Besi Kotak Hollow Penyangga Lembaran ACP", "m²", "AHSP PUPR", "FASAD"),
        ("wi-acp-sekrup", "DIN.044", "Pemasangan Lembaran ACP Pengunci Sekrup Drilling Tanam", "m²", "AHSP PUPR", "FASAD"),
        ("wi-nat-acp", "DIN.045", "Pengisian Nat Lembaran ACP Paku Silikon Sealant Eksterior", "m'", "AHSP PUPR", "FASAD"),
        ("wi-kaca-mati-8mm", "DIN.046", "Pemasangan Jendela Kaca Mati Ukuran Besar Fasad Depan (Tebal 8mm)", "m²", "AHSP PUPR", "FASAD"),
        ("wi-wpc-dinding-luar", "DIN.047", "Pemasangan Ornamen Kisi-Kisi Kayu Sintetis (WPC) Dinding Luar", "m²", "AHSP PUPR", "FASAD"),
        ("wi-keramik-dinding-km", "DIN.048", "Pemasangan Dinding Kamar Mandi Bahan Keramik 30x60 cm Motif Marmer", "m²", "SNI 7395", "DINDING"),
        ("wi-grouting-nat-keramik", "DIN.049", "Pengisian Nat Keramik Dinding Kamar Mandi Paku Semen Warna Grout", "m²", "AHSP PUPR", "DINDING"),
        ("wi-batako-pagar", "DIN.050", "Pasangan Batako untuk Konstruksi Pagar Keliling Samping Rumah", "m²", "AHSP PUPR", "DINDING"),
        ("wi-plester-pagar", "DIN.051", "Pekerjaan Plesteran & Acian Halus Pagar Keliling Samping", "m²", "AHSP PUPR", "DINDING"),
        ("wi-topi-beton", "DIN.052", "Pembuatan Topi-Topi Beton Pelindung Jendela dari Air Hujan", "m'", "AHSP PUPR", "DINDING"),
        ("wi-glass-block", "DIN.053", "Pemasangan Ornamen Glass Block Tebal pada Dinding Tangga", "m²", "AHSP PUPR", "DINDING"),
        ("wi-kamprot-ekspos", "DIN.054", "Pekerjaan Pembentukan Tekstur Kamprot Semen Semi-Kasar Dinding Luar", "m²", "AHSP PUPR", "DINDING"),
        ("wi-acian-ekspos-clear", "DIN.055", "Pekerjaan Finishing Acian Semen Ekspos Halus Proteksi Clear Coating", "m²", "AHSP PUPR", "DINDING"),
    ]
    for args in items:
        kg.add_work_item(WorkItemNode(*args))
    print(f"  ✅ Dinding, Kusen & Fasad: {len(items)} item pekerjaan dimuat")
