"""Domain Work Item: Instalasi Elektrikal & Teknologi Pintar - Kelompok VII"""
def load_wi_elektrikal(kg):
    from fastra_core.knowledge.nodes import WorkItemNode
    items = [
        ("wi-kwh-meter", "ELE.001", "Pemasangan KWH Meter Listrik Baru Khusus dari PLN Depan Rumah", "unit", "PUIL", "ELEKTRIKAL"),
        ("wi-panel-listrik-utama", "ELE.002", "Pemasangan Kotak Panel Listrik Utama Master (Distribution Board) Dalam", "unit", "PUIL", "ELEKTRIKAL"),
        ("wi-mcb-3phase", "ELE.003", "Pemasangan Unit Master MCB 3 Phase Pemutus Arus Utama Gedung", "unit", "PUIL", "ELEKTRIKAL"),
        ("wi-mcb-pembagi", "ELE.004", "Pemasangan Unit MCB Pembagi Arus Tiap-Tiap Lantai & Kelompok Ruang", "unit", "PUIL", "ELEKTRIKAL"),
        ("wi-bobokan-konduit", "ELE.005", "Bobokan Dinding Bata untuk Jalur Pipa Konduit Saklar & Stopkontak", "m'", "AHSP PUPR", "ELEKTRIKAL"),
        ("wi-pipa-konduit-20mm", "ELE.006", "Pemasangan Pipa Pelindung Kabel Fleksibel Konduit PVC 20mm Dinding", "m'", "PUIL", "ELEKTRIKAL"),
        ("wi-inbow-doos", "ELE.007", "Pemasangan Kotak Sambungan Kabel (Inbow Doos) Saklar Tanam Dinding", "buah", "PUIL", "ELEKTRIKAL"),
        ("wi-kabel-feeder-lt2", "ELE.008", "Penarikan Kabel Induk NYM 3x4mm dari Panel Utama ke Sub-Panel Lantai 2", "m'", "PUIL", "ELEKTRIKAL"),
        ("wi-kabel-stopkontak", "ELE.009", "Penarikan Kabel Jalur Stopkontak Standar Jenis NYM 3x2.5mm (SNI)", "m'", "PUIL", "ELEKTRIKAL"),
        ("wi-kabel-lampu", "ELE.010", "Penarikan Kabel Jalur Lampu Penerangan Jenis NYM 2x1.5mm (SNI)", "m'", "PUIL", "ELEKTRIKAL"),
        ("wi-kabel-grounding", "ELE.011", "Penarikan Kabel Khusus Grounding Arde Hijau-Kuning Menuju Pasak Tanah", "m'", "PUIL", "ELEKTRIKAL"),
        ("wi-tdos-plafon", "ELE.012", "Pemasangan Kotak Percabangan Kabel (T-Dos / Cross-Dos) Plafon", "buah", "PUIL", "ELEKTRIKAL"),
        ("wi-lasdop", "ELE.013", "Penyambungan Puntir Kabel Sambungan & Pembungkusan Isolasi Lasdop PVC", "titik", "PUIL", "ELEKTRIKAL"),
        ("wi-saklar-tunggal", "ELE.014", "Pemasangan Unit Saklar Tunggal Tanam Merek Schneider/Panasonic", "buah", "PUIL", "ELEKTRIKAL"),
        ("wi-saklar-ganda", "ELE.015", "Pemasangan Unit Saklar Ganda (Dua Tombol) Tanam Dinding", "buah", "PUIL", "ELEKTRIKAL"),
        ("wi-saklar-tukar", "ELE.016", "Pemasangan Unit Saklar Hotel (Saklar Tukar Tangga Lantai 1 & 2)", "buah", "PUIL", "ELEKTRIKAL"),
        ("wi-stopkontak-standar", "ELE.017", "Pemasangan Unit Stopkontak Standar Lengkap Pin Grounding Keselamatan", "buah", "PUIL", "ELEKTRIKAL"),
        ("wi-stopkontak-ac", "ELE.018", "Pemasangan Unit Stopkontak Khusus AC Daya Tinggi Lengkap Saklar On/Off", "buah", "PUIL", "ELEKTRIKAL"),
        ("wi-floor-socket", "ELE.019", "Pemasangan Unit Stopkontak Tanam Lantai Bahan Kuningan (Floor Socket)", "buah", "PUIL", "ELEKTRIKAL"),
        ("wi-kabel-lan", "ELE.020", "Penarikan Jalur Kabel Data Internet LAN Cat6 dari Posisi Hub ke Kamar", "m'", "AHSP PUPR", "ELEKTRIKAL"),
        ("wi-kabel-tv", "ELE.021", "Penarikan Jalur Kabel Antena Koaksial TV ke Titik Ruang Keluarga", "m'", "AHSP PUPR", "ELEKTRIKAL"),
        ("wi-terminal-rj45", "ELE.022", "Pemasangan Unit Terminal Stopkontak Data RJ45 & Terminal TV Dinding", "buah", "AHSP PUPR", "ELEKTRIKAL"),
        ("wi-downlight-3in", "ELE.023", "Pemasangan Rumah Lampu Tanam Plafon (Downlight Fixture) Diameter 3 Inci", "buah", "PUIL", "ELEKTRIKAL"),
        ("wi-lampu-smart-9w", "ELE.024", "Pemasangan Lampu LED Bulb Smart Home 9 Watt (Bisa Atur Warna Via Wifi)", "buah", "PUIL", "ELEKTRIKAL"),
        ("wi-double-head-gimbals", "ELE.025", "Pemasangan Rumah Lampu Tanam Plafon Kotak (Double Head Gimbals)", "buah", "PUIL", "ELEKTRIKAL"),
        ("wi-spotlight-lukisan", "ELE.026", "Pemasangan Lampu Sorot LED (Spotlight) Menyorot Lukisan Dinding", "buah", "PUIL", "ELEKTRIKAL"),
        ("wi-led-strip-plafon", "ELE.027", "Pemasangan Jalur Lampu Sembunyi Plafon (LED Strip Semak) Drop Ceiling", "m'", "PUIL", "ELEKTRIKAL"),
        ("wi-driver-led", "ELE.028", "Pemasangan Unit Transformator / Driver LED Strip Plafon Atas", "unit", "PUIL", "ELEKTRIKAL"),
        ("wi-lampu-gantung-kristal", "ELE.029", "Pemasangan Lampu Gantung Hias Kristal Besar Tengah Ruang Tamu", "unit", "PUIL", "ELEKTRIKAL"),
        ("wi-lampu-dinding-outdoor", "ELE.030", "Pemasangan Lampu Dinding Outdoor Tahan Air Teras Depan Rumah", "buah", "PUIL", "ELEKTRIKAL"),
        ("wi-spike-led", "ELE.031", "Pemasangan Lampu Sorot Taman Kedap Air (Spike LED Spotlight IP65)", "buah", "PUIL", "ELEKTRIKAL"),
        ("wi-in-ground-uplight", "ELE.032", "Pemasangan Lampu Tanam Lantai Carport (In-ground Uplight IP67)", "buah", "PUIL", "ELEKTRIKAL"),
        ("wi-pir-sensor", "ELE.033", "Pemasangan Sistem Saklar Otomatis Sensor Gerak (PIR Sensor) Toilet", "unit", "PUIL", "ELEKTRIKAL"),
        ("wi-smart-home-gateway", "ELE.034", "Pemasangan Hub Sentral Smart Home Gateway Pusat Kontrol Nirkabel", "unit", "AHSP PUPR", "ELEKTRIKAL"),
        ("wi-smart-switch", "ELE.035", "Pemasangan Modul Saklar Pintar Smart Switch Terkoneksi Asisten Suara", "unit", "AHSP PUPR", "ELEKTRIKAL"),
        ("wi-cctv-dome", "ELE.036", "Pemasangan Kamera Pengawas CCTV Jenis Dome Indoor Kamar Anak", "unit", "AHSP PUPR", "ELEKTRIKAL"),
        ("wi-cctv-bullet", "ELE.037", "Pemasangan Kamera Pengawas CCTV Jenis Bullet Outdoor Tahan Air Sudut Luar", "unit", "AHSP PUPR", "ELEKTRIKAL"),
        ("wi-kabel-poe", "ELE.038", "Penarikan Kabel LAN PoE (Power over Ethernet) Khusus Jaringan CCTV", "m'", "AHSP PUPR", "ELEKTRIKAL"),
        ("wi-nvr-cctv", "ELE.039", "Pemasangan Unit Perekam Video CCTV (NVR - Network Video Recorder)", "unit", "AHSP PUPR", "ELEKTRIKAL"),
        ("wi-hdd-cctv", "ELE.040", "Pemasangan Harddisk Khusus CCTV Survailance 4 Terabyte dalam NVR", "unit", "AHSP PUPR", "ELEKTRIKAL"),
        ("wi-monitor-cctv", "ELE.041", "Pemasangan Monitor Kontrol Layar LED CCTV di Dalam Kamar Utama", "unit", "AHSP PUPR", "ELEKTRIKAL"),
        ("wi-smart-door-lock", "ELE.042", "Pemasangan Kunci Pintu Pintar (Smart Door Lock Fingerprint/Card) Pintu Utama", "unit", "AHSP PUPR", "ELEKTRIKAL"),
        ("wi-kabel-interkom", "ELE.043", "Penarikan Kabel Bel Rumah Utama Video Interkom dari Pagar ke Foyer", "m'", "AHSP PUPR", "ELEKTRIKAL"),
        ("wi-monitor-interkom", "ELE.044", "Pemasangan Unit Layar Video Interkom Monitor Dinding Dalam Foyer", "unit", "AHSP PUPR", "ELEKTRIKAL"),
        ("wi-kamera-bell", "ELE.045", "Pemasangan Unit Kamera Tombol Bel Pintu Tahan Cuaca Depan Pagar", "unit", "AHSP PUPR", "ELEKTRIKAL"),
        ("wi-grounding-petir", "ELE.046", "Penarikan Jalur Kabel Penangkal Petir Tembaga BC Menembus Tanah", "m'", "SNI 03-7015", "ELEKTRIKAL"),
        ("wi-bor-grounding", "ELE.047", "Pengeboran Tanah Kedalaman 6 Meter untuk Pasak Grounding Penangkal Petir", "titik", "SNI 03-7015", "ELEKTRIKAL"),
        ("wi-grounding-rod", "ELE.048", "Pemasangan Pasak Tembaga Padat (Grounding Rod) Diameter 5/8 Inci", "batang", "SNI 03-7015", "ELEKTRIKAL"),
        ("wi-bak-grounding", "ELE.049", "Pemasangan Bak Kontrol Khusus Titik Sambungan Grounding Penangkal Petir", "unit", "SNI 03-7015", "ELEKTRIKAL"),
        ("wi-elcb", "ELE.050", "Pemasangan Sistem Pengaman Kebocoran Arus Listrik (ELCB / RCCB) di Panel", "unit", "PUIL", "ELEKTRIKAL"),
        ("wi-exhaust-fan-km1", "ELE.051", "Pemasangan Unit Exhaust Fan Plafon Kamar Mandi 1 Sambungan Konduit Udara", "unit", "AHSP PUPR", "ELEKTRIKAL"),
        ("wi-exhaust-fan-km2", "ELE.052", "Pemasangan Unit Exhaust Fan Plafon Kamar Mandi 2 Sambungan Konduit Udara", "unit", "AHSP PUPR", "ELEKTRIKAL"),
        ("wi-kabel-water-heater", "ELE.053", "Penarikan Kabel Power untuk Unit Mesin Pemanas Air Kamar Mandi", "m'", "PUIL", "ELEKTRIKAL"),
        ("wi-kabel-kompor-induksi", "ELE.054", "Pemasangan Kabel Power Induk untuk Kompor Induksi Daya Besar Dapur", "m'", "PUIL", "ELEKTRIKAL"),
        ("wi-emergency-light", "ELE.055", "Pemasangan Lampu Darurat Otomatis (Emergency Wall Light) Area Tangga", "unit", "PUIL", "ELEKTRIKAL"),
        ("wi-sparing-speaker", "ELE.056", "Pemasangan Jalur Pipa Sparing Kabel Speaker Langit-Langit (Ceiling Speaker)", "m'", "AHSP PUPR", "ELEKTRIKAL"),
        ("wi-ceiling-speaker", "ELE.057", "Pemasangan Unit Speaker Plafon (Ceiling Speaker) Ruang Keluarga", "unit", "AHSP PUPR", "ELEKTRIKAL"),
        ("wi-access-point-lt1", "ELE.058", "Pemasangan Unit Penguat Sinyal Wifi Router (Access Point Ceiling) Lantai 1", "unit", "AHSP PUPR", "ELEKTRIKAL"),
        ("wi-access-point-lt2", "ELE.059", "Pemasangan Unit Penguat Sinyal Wifi Router (Access Point Ceiling) Lantai 2", "unit", "AHSP PUPR", "ELEKTRIKAL"),
        ("wi-sensor-gas", "ELE.060", "Pemasangan Sensor Kebocoran Gas Elpiji Kamar Dapur Koneksi Sirine Alarm", "unit", "AHSP PUPR", "ELEKTRIKAL"),
    ]
    for args in items:
        kg.add_work_item(WorkItemNode(*args))
    print(f"  ✅ Elektrikal & Smart Home: {len(items)} item pekerjaan dimuat")
