"""Domain Work Item: Finishing Lantai, Plafon & Dekorasi Interior - Kelompok VI"""
def load_wi_finishing(kg):
    from fastra_core.knowledge.nodes import WorkItemNode
    items = [
        ("wi-screeding-kt1", "FIN.001", "Pekerjaan Perataan Lantai Pasir Semen (Screeding) Kamar Tidur 1", "m²", "AHSP PUPR", "FINISHING"),
        ("wi-screeding-rt", "FIN.002", "Pekerjaan Perataan Lantai Pasir Semen (Screeding) Ruang Tamu", "m²", "AHSP PUPR", "FINISHING"),
        ("wi-screeding-kt2", "FIN.003", "Pekerjaan Perataan Lantai Pasir Semen (Screeding) Kamar Tidur 2", "m²", "AHSP PUPR", "FINISHING"),
        ("wi-granit-rt", "FIN.004", "Pemasangan Lantai Granit Tile Ukuran 60x60 cm Ruang Tamu Utama", "m²", "SNI 7395", "LANTAI"),
        ("wi-granit-kt1", "FIN.005", "Pemasangan Granit Tile Ukuran 60x60 cm Kamar Tidur Lantai 1", "m²", "SNI 7395", "LANTAI"),
        ("wi-granit-keluarga-lt2", "FIN.006", "Pemasangan Granit Tile Ukuran 60x60 cm Ruang Keluarga Lantai 2", "m²", "SNI 7395", "LANTAI"),
        ("wi-tile-adhesive", "FIN.007", "Penggunaan Semen Instan Pengikat Granit (Tile Adhesive Premium)", "m²", "AHSP PUPR", "LANTAI"),
        ("wi-keramik-km1", "FIN.008", "Pemasangan Lantai Keramik Kasar Anti Slip 30x30 cm Kamar Mandi 1", "m²", "SNI 7395", "LANTAI"),
        ("wi-keramik-km2", "FIN.009", "Pemasangan Lantai Keramik Kasar Anti Slip 30x30 cm Kamar Mandi 2", "m²", "SNI 7395", "LANTAI"),
        ("wi-keramik-carport", "FIN.010", "Pemasangan Lantai Keramik Kasar 40x40 cm Area Carport Depan", "m²", "SNI 7395", "LANTAI"),
        ("wi-step-nosing", "FIN.011", "Pemasangan Keramik Granit Tile Khusus Trap Anak Tangga (Step Nosing)", "m'", "AHSP PUPR", "LANTAI"),
        ("wi-riser-keramik", "FIN.012", "Pemasangan Keramik Bagian Vertikal Anak Tangga (Riser)", "m'", "AHSP PUPR", "LANTAI"),
        ("wi-bullnose", "FIN.013", "Pemotongan Pinggiran Granit Tile Metode Bullnose / Siku Tumpul", "m'", "AHSP PUPR", "LANTAI"),
        ("wi-plin-granit", "FIN.014", "Pemasangan Plin Granit Tile Tinggi 10 cm Batas Bawah Dinding", "m'", "AHSP PUPR", "LANTAI"),
        ("wi-epoxy-grout", "FIN.015", "Pekerjaan Pembersihan Sela Ubin & Pengisian Nat Granit Paku Epoxy Grout", "m²", "AHSP PUPR", "LANTAI"),
        ("wi-vinyl-lantai", "FIN.016", "Pemasangan Lantai Kayu Vinyl Tebal 4mm Sistem Click Kamar Utama", "m²", "AHSP PUPR", "LANTAI"),
        ("wi-foam-underlay", "FIN.017", "Pemasangan Lapisan Foam Underlayment Sebelum Pasang Lantai Vinyl", "m²", "AHSP PUPR", "LANTAI"),
        ("wi-list-transisi", "FIN.018", "Pemasangan List Transisi Aluminium Batas Granit & Vinyl Lantai", "m'", "AHSP PUPR", "LANTAI"),
        ("wi-rangka-plafon-2x4", "FIN.019", "Pemasangan Rangka Plafon Besi Hollow Galvalum 2x4 cm Ruang Tamu", "m²", "AHSP PUPR", "PLAFON"),
        ("wi-rangka-plafon-4x4", "FIN.020", "Pemasangan Rangka Plafon Besi Hollow Galvalum 4x4 cm Rangka Induk", "m²", "AHSP PUPR", "PLAFON"),
        ("wi-kawat-gantung-plafon", "FIN.021", "Pemasangan Kawat Penggantung Rangka Plafon Besi ke Plat Dak/Kaso", "titik", "AHSP PUPR", "PLAFON"),
        ("wi-gypsum-9mm", "FIN.022", "Pemasangan Lembaran Papan Gipsum Tebal 9mm untuk Plafon Dalam", "m²", "AHSP PUPR", "PLAFON"),
        ("wi-grc-plafon-km", "FIN.023", "Pemasangan Lembaran Papan GRC Board Tahan Lembab Plafon Kamar Mandi", "m²", "AHSP PUPR", "PLAFON"),
        ("wi-grc-plafon-teras", "FIN.024", "Pemasangan Lembaran Papan GRC Board Plafon Area Teras Luar", "m²", "AHSP PUPR", "PLAFON"),
        ("wi-drywall-screw", "FIN.025", "Pemasangan Sekrup Khusus Gipsum (Drywall Screw) Jarak Per 20 cm", "titik", "AHSP PUPR", "PLAFON"),
        ("wi-fiber-tape", "FIN.026", "Pemasangan Kassa Kain Fiber (Fiber Tape) Sambungan Papan Gipsum", "m'", "AHSP PUPR", "PLAFON"),
        ("wi-kompon-plafon", "FIN.027", "Pekerjaan Penutupan Sela Sambungan Gipsum Paku Bubuk Kompon Plafon", "m'", "AHSP PUPR", "PLAFON"),
        ("wi-amplas-kompon", "FIN.028", "Pekerjaan Pengampelasan Sambungan Kompon Plafon hingga Rata", "m'", "AHSP PUPR", "PLAFON"),
        ("wi-drop-ceiling", "FIN.029", "Pembuatan Variasi Plafon Turun Tingkat (Drop Ceiling) Ruang Tamu", "m²", "AHSP PUPR", "PLAFON"),
        ("wi-list-profil-gypsum", "FIN.030", "Pemasangan List Profil Gipsum Lebar 5 cm Keliling Tepi Plafon", "m'", "AHSP PUPR", "PLAFON"),
        ("wi-plamir-dinding", "FIN.031", "Pekerjaan Plamir Dasar Dinding Interior Lapisan Pengisi Pori-Pori", "m²", "SNI 2837", "CAT"),
        ("wi-amplas-plamir", "FIN.032", "Pekerjaan Pengampelasan Lapisan Plamir Dinding Interior", "m²", "SNI 2837", "CAT"),
        ("wi-cat-dasar-interior", "FIN.033", "Pengecatan Cat Dasar Interior Tahan Alkali (Alkali Resisting Primer)", "m²", "SNI 2837", "CAT"),
        ("wi-cat-interior-1", "FIN.034", "Pengecatan Cat Utama Interior Warna Pilihan Lapis 1", "m²", "SNI 2837", "CAT"),
        ("wi-cat-interior-2", "FIN.035", "Pengecatan Cat Utama Interior Warna Pilihan Lapis 2 (Warna Solid)", "m²", "SNI 2837", "CAT"),
        ("wi-cat-interior-3", "FIN.036", "Pengecatan Cat Utama Interior Warna Pilihan Lapis 3 (Finishing Akhir)", "m²", "SNI 2837", "CAT"),
        ("wi-plamir-plafon", "FIN.037", "Pekerjaan Plamir & Pengampelasan Permukaan Plafon Gipsum", "m²", "AHSP PUPR", "CAT"),
        ("wi-cat-plafon-1", "FIN.038", "Pengecatan Plafon Gipsum Dalam Warna Putih Matt Khusus Plafon Lapis 1", "m²", "AHSP PUPR", "CAT"),
        ("wi-cat-plafon-2", "FIN.039", "Pengecatan Plafon Gipsum Dalam Warna Putih Matt Khusus Plafon Lapis 2", "m²", "AHSP PUPR", "CAT"),
        ("wi-cat-dasar-luar", "FIN.040", "Pengecatan Dinding Luar Lapisan Cat Dasar Anti Karat/Zat Kapur", "m²", "SNI 2837", "CAT"),
        ("wi-cat-eksterior-1", "FIN.041", "Pengecatan Dinding Luar Cat Utama Tahan Cuaca Ekstrem (Weathershield) Lapis 1", "m²", "SNI 2837", "CAT"),
        ("wi-cat-eksterior-2", "FIN.042", "Pengecatan Dinding Luar Cat Utama Tahan Cuaca Ekstrem (Weathershield) Lapis 2", "m²", "SNI 2837", "CAT"),
        ("wi-cat-anti-jamur", "FIN.043", "Pengecatan Lapisan Cat Anti Jamur/Lumut pada Samping Pagar Rumah", "m²", "SNI 2837", "CAT"),
        ("wi-cat-duco-pintu", "FIN.044", "Finishing Cat Duco Warna Putih Semprot Daun Pintu Kamar", "m²", "SNI 2837", "CAT"),
        ("wi-politur-pintu", "FIN.045", "Finishing Kuas Politur Kayu / Melamik Daun Pintu Utama Kayu Jati", "m²", "SNI 2837", "CAT"),
        ("wi-wallpaper", "FIN.046", "Pemasangan Wallpaper Dinding Motif Minimalis Kamar Tidur Utama", "m²", "AHSP PUPR", "INTERIOR"),
        ("wi-lem-wallpaper", "FIN.047", "Pengolesan Lem Khusus Wallpaper Premium pada Dinding Acian Mulus", "m²", "AHSP PUPR", "INTERIOR"),
        ("wi-padded-wall", "FIN.048", "Pemasangan Panel Dinding Kain/Busa Empuk (Padded Wall Panel) Kepala Ranjang", "m²", "AHSP PUPR", "INTERIOR"),
        ("wi-cermin-bevel", "FIN.049", "Pemasangan Kaca Cermin Besar Bevel Tempel Dinding Ruang Makan", "m²", "AHSP PUPR", "INTERIOR"),
        ("wi-railing-tangga-besi", "FIN.050", "Pemasangan Railing Tangga Bahan Besi Hollow Minimalis Cat Hitam", "m'", "AHSP PUPR", "INTERIOR"),
        ("wi-handrail-kayu", "FIN.051", "Pemasangan Pegangan Tangan Railing Tangga (Handrail) Bahan Kayu Kamper", "m'", "AHSP PUPR", "INTERIOR"),
        ("wi-railing-balkon", "FIN.052", "Pemasangan Railing Pembatas Balkon Atas Bahan Besi & Kaca Tempered", "m'", "AHSP PUPR", "INTERIOR"),
        ("wi-sekat-foyer", "FIN.053", "Pemasangan Kisi-Kisi Sekat Ruangan Pembatas Foyer & Ruang Tamu Bahan Kayu", "m²", "AHSP PUPR", "INTERIOR"),
        ("wi-bata-terakota", "FIN.054", "Pemasangan Variasi Batu Bata Tempel Terakota Dinding Interior Belakang", "m²", "AHSP PUPR", "INTERIOR"),
        ("wi-karpet-tile", "FIN.055", "Pemasangan Karpet Tile Lantai Ruang Kerja / Studio Interior Home Teater", "m²", "AHSP PUPR", "INTERIOR"),
    ]
    for args in items:
        kg.add_work_item(WorkItemNode(*args))
    print(f"  ✅ Finishing Lantai, Plafon & Dekorasi: {len(items)} item pekerjaan dimuat")
