"""Domain Work Item: Interior & Fit-Out Custom - Kelompok XVIII"""
def load_wi_interior(kg):
    from fastra_core.knowledge.nodes import WorkItemNode
    items = [
        ("wi-site-marking", "INT.001", "Pekerjaan Site Marking Interior: Garis Pola Furnitur Skala 1:1 di Lantai", "m²", "AHSP PUPR", "INTERIOR"),
        ("wi-partisi-double-stud", "INT.002", "Pemasangan Rangka Dinding Partisi Double Stud (Insulasi Suara Maksimal)", "m²", "AHSP PUPR", "INTERIOR"),
        ("wi-mdf-backing", "INT.003", "Pemasangan Papan MDF / Multiplek Backing Dinding", "m²", "AHSP PUPR", "INTERIOR"),
        ("wi-hpl-laminasi", "INT.004", "Pemasangan HPL (High Pressure Laminate) Motif Kayu/Marmer", "m²", "AHSP PUPR", "INTERIOR"),
        ("wi-edging-pvc", "INT.005", "Pemasangan Edging PVC Otomatis Pinggiran Furnitur", "m'", "AHSP PUPR", "INTERIOR"),
        ("wi-edging-akrilik", "INT.006", "Pemasangan Edging Akrilik / 3D Edging Premium", "m'", "AHSP PUPR", "INTERIOR"),
        ("wi-cat-duco-plamir", "INT.007", "Finishing Cat Duco - Tahap Plamir Kayu", "m²", "AHSP PUPR", "INTERIOR"),
        ("wi-cat-duco-dasar", "INT.008", "Finishing Cat Duco - Tahap Cat Dasar (Surfacer)", "m²", "AHSP PUPR", "INTERIOR"),
        ("wi-cat-duco-warna", "INT.009", "Finishing Cat Duco - Tahap Warna Utama (Matt/Glossy/Satin)", "m²", "AHSP PUPR", "INTERIOR"),
        ("wi-cat-duco-topcoat", "INT.010", "Finishing Cat Duco - Tahap Clear Coat / Top Coat Pelindung", "m²", "AHSP PUPR", "INTERIOR"),
        ("wi-melamic-politur", "INT.011", "Finishing Melamic / Politur Semprot Transparan Serat Kayu", "m²", "AHSP PUPR", "INTERIOR"),
        ("wi-engsel-softclose", "INT.012", "Pemasangan Engsel Soft-Close / Slow-Motion Pintu Lemari", "set", "AHSP PUPR", "INTERIOR"),
        ("wi-rel-laci-undermount", "INT.013", "Pemasangan Rel Laci Double Track Under-Mount (Beban Berat)", "set", "AHSP PUPR", "INTERIOR"),
        ("wi-push-to-open", "INT.014", "Pemasangan Rel Laci Sistem Push-to-Open (Tanpa Handle)", "set", "AHSP PUPR", "INTERIOR"),
        ("wi-over-x-sliding", "INT.015", "Pemasangan Sistem Pintu Geser Lemari Over-X (Sejajar Rapi)", "set", "AHSP PUPR", "INTERIOR"),
        ("wi-wardrobe-lift", "INT.016", "Pemasangan Gantungan Baju Sistem Tarik (Pull-Down Wardrobe Lift)", "unit", "AHSP PUPR", "INTERIOR"),
        ("wi-lazy-susan", "INT.017", "Pemasangan Rak Dapur Sudut Putar (Lazy Susan / Magic Corner)", "unit", "AHSP PUPR", "INTERIOR"),
        ("wi-rak-piring-tarik", "INT.018", "Pemasangan Rak Piring Tarik Stainless Steel Dalam Kabinet Atas", "unit", "AHSP PUPR", "INTERIOR"),
        ("wi-led-strip-lemari", "INT.019", "Pemasangan Lampu LED Strip Sensor Buka Pintu Dalam Lemari", "unit", "AHSP PUPR", "INTERIOR"),
        ("wi-led-kolong-kabinet", "INT.020", "Pemasangan Lampu LED Indirect Kolong Kabinet Dapur", "m'", "AHSP PUPR", "INTERIOR"),
        ("wi-led-profile", "INT.021", "Pemasangan Profil Aluminium LED (LED Profile/Channel) Penanam Strip", "m'", "AHSP PUPR", "INTERIOR"),
        ("wi-popup-socket", "INT.022", "Pemasangan Stop Kontak Tanam Meja Sistem Putar (Rotatable Pop-Up Socket)", "unit", "AHSP PUPR", "INTERIOR"),
        ("wi-padded-headboard", "INT.023", "Pemasangan Kepala Ranjang Bungkus Kain (Padded Headboard)", "unit", "AHSP PUPR", "INTERIOR"),
        ("wi-cermin-berlian", "INT.024", "Pemasangan Kaca Cermin Bevel Berpola (Pola Berlian/Kotak Dinding)", "m²", "AHSP PUPR", "INTERIOR"),
        ("wi-wall-moulding", "INT.025", "Pemasangan Wall Moulding Klasik (Bahan Kayu/PVC) Gaya American Classic", "m'", "AHSP PUPR", "INTERIOR"),
        ("wi-wpc-kisi-interior", "INT.026", "Pemasangan Kisi-Kisi WPC (Wood Plastic Composite) Interior", "m²", "AHSP PUPR", "INTERIOR"),
        ("wi-fluted-akrilik", "INT.027", "Pemasangan Fluted Panel Akrilik Dinding Gelombang", "m²", "AHSP PUPR", "INTERIOR"),
        ("wi-top-table-kuarsa", "INT.028", "Pemasangan Top Table Kuarsa (Quartz Surface) Meja Dapur", "m'", "AHSP PUPR", "INTERIOR"),
        ("wi-top-table-marmer", "INT.029", "Pemasangan Top Table Marmer Alami + Coating Sealer", "m'", "AHSP PUPR", "INTERIOR"),
        ("wi-cowakan-sink", "INT.030", "Pekerjaan Cowakan Sink Joint (Top Table) - Potong Melingkar Presisi", "unit", "AHSP PUPR", "INTERIOR"),
        ("wi-siku-pinggul", "INT.031", "Pekerjaan Siku Pinggul / Bullnose Granit Penggerindaan Sudut Tumpul", "m'", "AHSP PUPR", "INTERIOR"),
        ("wi-kaca-backsplash", "INT.032", "Pemasangan Kaca Backsplash Dapur (Tempered Lacobel) Anti Minyak", "m²", "AHSP PUPR", "INTERIOR"),
        ("wi-subway-tile", "INT.033", "Pemasangan Keramik Motif Subway Tile Dapur + Semen Nat Kontras", "m²", "AHSP PUPR", "INTERIOR"),
        ("wi-vinyl-lantai-click", "INT.034", "Pemasangan Vinyl Lantai Sistem Click Tanpa Lem Motif Kayu", "m²", "AHSP PUPR", "INTERIOR"),
        ("wi-spc-lantai", "INT.035", "Pemasangan Lantai SPC (Stone Plastic Composite) 100% Tahan Air", "m²", "AHSP PUPR", "INTERIOR"),
        ("wi-karpet-tile-kantor", "INT.036", "Pemasangan Karpet Tile Kantor Berperekat Khusus", "m²", "AHSP PUPR", "INTERIOR"),
        ("wi-gorden-blackout", "INT.037", "Pemasangan Gorden Sistem Blackout 100% Penahan Cahaya", "m'", "AHSP PUPR", "INTERIOR"),
        ("wi-vitrase-gorden", "INT.038", "Pemasangan Vitrase Gorden (Kain Tipis Transparan Putih)", "m'", "AHSP PUPR", "INTERIOR"),
        ("wi-roller-blinds", "INT.039", "Pemasangan Jendela Gulung Roller Blinds / Zebra Blinds Rantai Tarik", "unit", "AHSP PUPR", "INTERIOR"),
        ("wi-handrail-custom", "INT.040", "Pemasangan Pegangan Tangan Tangga Kayu Custom (Meliuk Ikuti Tangga)", "m'", "AHSP PUPR", "INTERIOR"),
        ("wi-rotating-louvre", "INT.041", "Pemasangan Kisi-Kisi Penyekat Ruangan Pusing (Rotating Louvre Louver)", "m²", "AHSP PUPR", "INTERIOR"),
        ("wi-barrisol-ceiling", "INT.042", "Pemasangan Plafon Kain Kelambu Regang (Barrisol Ceiling) LED Massal", "m²", "AHSP PUPR", "INTERIOR"),
        ("wi-sound-diffuser", "INT.043", "Pemasangan Panel Akustik Penyerap Gema (Sound Diffuser) Ruang Karaoke", "m²", "AHSP PUPR", "INTERIOR"),
        ("wi-rfid-cabinet-lock", "INT.044", "Pemasangan Kunci Lemari Sistem Kartu (RFID Cabinet Lock) Elektronik", "unit", "AHSP PUPR", "INTERIOR"),
        ("wi-de-formaldehyde", "INT.045", "Pembersihan Uap Furnitur Baru (De-formaldehyde Treatment) Aman Hirup", "unit", "AHSP PUPR", "INTERIOR"),
    ]
    for args in items:
        kg.add_work_item(WorkItemNode(*args))
    print(f"  ✅ Interior & Fit-Out: {len(items)} item pekerjaan dimuat")
