"""Domain Work Item: Plumbing, Saluran Air & Sanitasi - Kelompok VIII"""
def load_wi_plumbing(kg):
    from fastra_core.knowledge.nodes import WorkItemNode
    items = [
        ("wi-submersible-pump", "PLU.001", "Pemasangan Mesin Pompa Air Tanah Sumur Dalam (Submersible Pump)", "unit", "AHSP PUPR", "PLUMBING"),
        ("wi-pipa-isap-1in", "PLU.002", "Penarikan Pipa Isap PVC AW 1 Inci Turun ke Dalam Sumur Bor", "m'", "SNI Plumbing", "PLUMBING"),
        ("wi-kabel-submersible", "PLU.003", "Pemasangan Kabel Power Waterproof Motor Submersible Pump ke Atas", "m'", "SNI Plumbing", "PLUMBING"),
        ("wi-pressure-switch", "PLU.004", "Pemasangan Alat Otomatis Pompa Tekanan Air (Pressure Switch / Radar)", "unit", "SNI Plumbing", "PLUMBING"),
        ("wi-filter-tabung-1054", "PLU.005", "Pemasangan Tabung Filter Air Tabung Serat Fiber Tinggi Tipe 1054 Depan", "unit", "AHSP PUPR", "PLUMBING"),
        ("wi-media-filter", "PLU.006", "Pengisian Media Filter Pasir Silika & Karbon Aktif Dalam Tabung Filter", "unit", "AHSP PUPR", "PLUMBING"),
        ("wi-pipa-ppr-lt1", "PLU.007", "Pemasangan Pipa Distribusi Air Bersih Utama Pipa PPR PN-10 Lantai 1", "m'", "SNI Plumbing", "PLUMBING"),
        ("wi-pipa-ppr-lt2", "PLU.008", "Pemasangan Pipa Distribusi Air Bersih Utama Pipa PPR PN-10 Lantai 2", "m'", "SNI Plumbing", "PLUMBING"),
        ("wi-pipa-air-panas", "PLU.009", "Pemasangan Pipa Air Panas Khusus Tebal PPR PN-20 Jalur Kamar Mandi", "m'", "SNI Plumbing", "PLUMBING"),
        ("wi-bobokan-pipa", "PLU.010", "Bobokan Dinding Bata untuk Penanaman Jalur Pipa PPR Air Bersih", "m'", "AHSP PUPR", "PLUMBING"),
        ("wi-polyfusion-las", "PLU.011", "Penyambungan Pipa PPR Metode Las Panas Paku Mesin PPR Polyfusion", "titik", "SNI Plumbing", "PLUMBING"),
        ("wi-gate-valve", "PLU.012", "Pemasangan Kran Stop Utama (Gate Valve) Kuningan Tiap Lantai", "unit", "SNI Plumbing", "PLUMBING"),
        ("wi-menara-toren", "PLU.013", "Pemasangan Menara Besi Siku / Dudukan Dak Beton Tempat Toren Air Atas", "unit", "AHSP PUPR", "PLUMBING"),
        ("wi-toren-1000l", "PLU.014", "Pemasangan Tangki Air Atas (Toren) Bahan Plastik HDPE Kapasitas 1000L", "unit", "AHSP PUPR", "PLUMBING"),
        ("wi-radar-toren", "PLU.015", "Pemasangan Unit Kran Pelampung Otomatis (Radar Toren) Dalam Tangki Air", "unit", "AHSP PUPR", "PLUMBING"),
        ("wi-booster-pump", "PLU.016", "Pemasangan Pompa Air Pendorong Tekanan (Booster Pump Inverter) Setelah Toren", "unit", "AHSP PUPR", "PLUMBING"),
        ("wi-pipa-kotor-4in", "PLU.017", "Pemasangan Pipa Pembuangan Air Kotor Kloset Pipa PVC Kelas AW 4 Inci", "m'", "SNI Plumbing", "PLUMBING"),
        ("wi-pipa-bekas-3in", "PLU.018", "Pemasangan Pipa Pembuangan Air Bekas Mandi/Wastafel Pipa PVC AW 3 Inci", "m'", "SNI Plumbing", "PLUMBING"),
        ("wi-pipa-hujan-3in", "PLU.019", "Pemasangan Pipa Pembuangan Air Hujan Atas Pipa PVC Kelas AW 3 Inci", "m'", "SNI Plumbing", "PLUMBING"),
        ("wi-elbow-pvc", "PLU.020", "Pemasangan Sambungan Siku Pipa (Elbow) PVC AW Tebal Tiap Belokan Jalur", "buah", "SNI Plumbing", "PLUMBING"),
        ("wi-y-branch", "PLU.021", "Pemasangan Sambungan Huruf Y (Y-Branch) Pipa Pembuangan Air Kotor", "buah", "SNI Plumbing", "PLUMBING"),
        ("wi-lem-pipa-pvc", "PLU.022", "Pengolesan Lem Pipa PVC Mutu Tinggi Sambungan Rapat Anti Bocor", "titik", "SNI Plumbing", "PLUMBING"),
        ("wi-galian-septic", "PLU.023", "Galian Tanah Kompleks untuk Kamar Tangki Septic Tank Pabrikan (Biotank)", "m³", "AHSP PUPR", "PLUMBING"),
        ("wi-plat-dasar-biotank", "PLU.024", "Pengecoran Plat Beton Dasar Dudukan Tangki Biotank Bawah Tanah", "m³", "AHSP PUPR", "PLUMBING"),
        ("wi-penurunan-biotank", "PLU.025", "Penurunan Unit Tangki Biotank Kapasitas Volume Rumah Tangga 5 Orang", "unit", "AHSP PUPR", "PLUMBING"),
        ("wi-pengisian-air-biotank", "PLU.026", "Pengisian Air Bersih Tangki Biotank & Uji Kebocoran Awal", "unit", "AHSP PUPR", "PLUMBING"),
        ("wi-pipa-vent-plumbing", "PLU.027", "Instalasi Pipa Udara Venting Plambing 1.5 Inci Naik ke Atas Atap", "m'", "SNI Plumbing", "PLUMBING"),
        ("wi-bak-kontrol-plumbing", "PLU.028", "Pembuatan Bak Kontrol Saluran Plambing Beton Mini + Tutup Besi", "unit", "AHSP PUPR", "PLUMBING"),
        ("wi-kloset-duduk", "PLU.029", "Pemasangan Kloset Duduk Porselen + Baut Silet Dynabolt + Wax Ring", "unit", "AHSP PUPR", "PLUMBING"),
        ("wi-wastafel-gantung", "PLU.030", "Pemasangan Wastafel Cuci Muka Gantung Dinding + Kran Pencampur", "unit", "AHSP PUPR", "PLUMBING"),
        ("wi-shower-mandi", "PLU.031", "Pemasangan Tiang Pancuran Shower Mandi + Mixer Panas Dingin", "unit", "AHSP PUPR", "PLUMBING"),
        ("wi-aksesoris-km", "PLU.032", "Pemasangan Aksesoris Gantung Kamar Mandi (Handuk, Sabun, Tisu, Floor Drain)", "set", "AHSP PUPR", "PLUMBING"),
        ("wi-kitchen-sink", "PLU.033", "Pemasangan Bak Cuci Piring Dapur (Kitchen Sink) Stainless + Kran", "unit", "AHSP PUPR", "PLUMBING"),
        ("wi-hydrotest", "PLU.034", "Uji Tekan Jaringan Pipa Air (Hydrostatic Test) 8-10 Bar Selama 24 Jam", "unit", "SNI Plumbing", "PLUMBING"),
        ("wi-pompa-sumur-dangkal", "PLU.035", "Pemasangan Mesin Pompa Sumur Dangkal / Jetpump", "unit", "AHSP PUPR", "PLUMBING"),
        ("wi-ground-tank", "PLU.036", "Pembuatan Bak Tampung Air Bawah Tanah (Ground Tank) Beton", "m³", "SNI 2847", "PLUMBING"),
        ("wi-waterproofing-gt", "PLU.037", "Pemasangan Lapisan Waterproofing Semen Base Dalam Ground Tank", "m²", "AHSP PUPR", "PLUMBING"),
        ("wi-sparing-gt", "PLU.038", "Pemasangan Pipa Sparing Inlet/Outlet Tembus Dinding Ground Tank", "titik", "AHSP PUPR", "PLUMBING"),
        ("wi-manhole-gt", "PLU.039", "Pemasangan Manhole Cover Besi Cor untuk Penutup Ground Tank", "unit", "AHSP PUPR", "PLUMBING"),
        ("wi-water-heater-listrik", "PLU.040", "Instalasi Unit Pemanas Air Listrik (Storage Heater) 30L", "unit", "AHSP PUPR", "PLUMBING"),
        ("wi-water-heater-gas", "PLU.041", "Instalasi Unit Pemanas Air Gas Instan Kamar Mandi", "unit", "AHSP PUPR", "PLUMBING"),
        ("wi-solar-water-heater", "PLU.042", "Pemasangan Solar Water Heater + Kolektor Panel di Atap", "unit", "AHSP PUPR", "PLUMBING"),
        ("wi-pipa-tembaga-ac", "PLU.043", "Pemasangan Pipa Tembaga AC + Isolasi Pendingin", "m'", "AHSP PUPR", "PLUMBING"),
        ("wi-drainase-bawah-tanah", "PLU.044", "Pemasangan Pipa Sub-Drain Lapisan Bawah (Pipa Berlubang Bungkus Ijuk)", "m'", "AHSP PUPR", "PLUMBING"),
        ("wi-sumur-resapan-hujan", "PLU.045", "Pembuatan Sumur Resapan Air Hujan Lapangan (Konservasi Air)", "unit", "AHSP PUPR", "PLUMBING"),
        ("wi-pipa-gas-dapur", "PLU.046", "Instalasi Pipa Gas Sentral Dapur (Pipa Tembaga Tebal Khusus)", "m'", "SNI Plumbing", "PLUMBING"),
        ("wi-gas-detector", "PLU.047", "Pemasangan Detektor Kebocoran Gas & Solenoid Valve Otomatis Dapur", "unit", "SNI Plumbing", "PLUMBING"),
        ("wi-toren-500l", "PLU.048", "Pemasangan Tangki Air Atas (Toren) Bahan Plastik HDPE Kapasitas 500L", "unit", "AHSP PUPR", "PLUMBING"),
        ("wi-pompa-booster-inverter", "PLU.049", "Pemasangan Pompa Dorong Tekanan Konstan (Inverter Pump) Hemat Listrik", "unit", "AHSP PUPR", "PLUMBING"),
        ("wi-filter-sentral", "PLU.050", "Instalasi Sistem Penyaring Air Utama (Water Filter Central) Pasir + Karbon", "unit", "AHSP PUPR", "PLUMBING"),
        ("wi-roof-drain-castiron", "PLU.051", "Pemasangan Roof Drain Cast Iron Saringan Dak Beton Atas", "unit", "AHSP PUPR", "PLUMBING"),
        ("wi-pipa-air-kotor-2in", "PLU.052", "Pemasangan Pipa Pembuangan Air Kotor 2 Inci untuk Wastafel", "m'", "SNI Plumbing", "PLUMBING"),
        ("wi-pipe-clamp", "PLU.053", "Pemasangan Klem Pipa Air (Pipe Clamp/Hanger) Dudukan Besi Gantung", "buah", "SNI Plumbing", "PLUMBING"),
        ("wi-flexible-joint", "PLU.054", "Pemasangan Flexible Joint Pipa (Karet/Kawat Anyam) Peredam Getaran Pompa", "unit", "SNI Plumbing", "PLUMBING"),
        ("wi-clean-out", "PLU.055", "Pemasangan Clean Out Pipa Air Kotor (Lubang Sumbat Berulir) Akses Bersih", "unit", "SNI Plumbing", "PLUMBING"),
    ]
    for args in items:
        kg.add_work_item(WorkItemNode(*args))
    print(f"  ✅ Plumbing & Sanitasi: {len(items)} item pekerjaan dimuat")
