"""Domain Work Item: Struktur Utama Atas (Kelompok III)"""
def load_wi_struktur_atas(kg):
    from fastra_core.knowledge.nodes import WorkItemNode
    items = [
        ("wi-sloof-rebar-fab", "STR.001", "Fabrikasi Tulangan Besi Pokok Ulir D16 untuk Sloof Beton", "kg", "SNI 2847", "STRUKTUR_ATAS"),
        ("wi-sloof-sengkang", "STR.002", "Fabrikasi Tulangan Sengkang Besi Polos ø8 untuk Sloof", "kg", "SNI 2847", "STRUKTUR_ATAS"),
        ("wi-sloof-rebar-assembly", "STR.003", "Perakitan Tulangan Sloof Besi di Atas Pondasi", "kg", "SNI 2847", "STRUKTUR_ATAS"),
        ("wi-sloof-spacer", "STR.004", "Pemasangan Tahu Beton / Spacer Pengatur Selimut Beton Sloof", "buah", "AHSP PUPR", "STRUKTUR_ATAS"),
        ("wi-sloof-bekisting", "STR.005", "Pemasangan Bekisting Papan Kayu untuk Sloof 20x30 cm", "m'", "AHSP PUPR", "STRUKTUR_ATAS"),
        ("wi-sloof-cor", "STR.006", "Pengecoran Beton Sloof Mutu K-250 Ready Mix", "m³", "SNI 2847", "STRUKTUR_ATAS"),
        ("wi-sloof-bongkar-bekisting", "STR.007", "Pembongkaran Bekisting Kayu Sloof Setelah 24 Jam", "m'", "AHSP PUPR", "STRUKTUR_ATAS"),
        ("wi-sloof-curing", "STR.008", "Perawatan Beton Sloof Menggunakan Siraman Air (Curing)", "m'", "SNI 2847", "STRUKTUR_ATAS"),
        ("wi-kolom-lt1-rebar-fab", "STR.009", "Fabrikasi Tulangan Kolom Utama Struktur Lantai 1 (Besi D19)", "kg", "SNI 2847", "STRUKTUR_ATAS"),
        ("wi-kolom-lt1-sengkang", "STR.010", "Perakitan Sengkang Kolom Utama dengan Jarak Sesuai Gambar", "kg", "SNI 2847", "STRUKTUR_ATAS"),
        ("wi-kolom-stek-sambung", "STR.011", "Penyambungan Besi Stek Kolom Lantai Dasar ke Sloof (Overlapping)", "titik", "SNI 2847", "STRUKTUR_ATAS"),
        ("wi-kolom-bekisting", "STR.012", "Pemasangan Bekisting Kolom Utama Bahan Plywood Tebal 15mm", "m²", "AHSP PUPR", "STRUKTUR_ATAS"),
        ("wi-kolom-kaso-pengaku", "STR.013", "Pemasangan Rangka Kayu Kaso Pengaku Bekisting Kolom", "m'", "AHSP PUPR", "STRUKTUR_ATAS"),
        ("wi-kolom-scaffolding", "STR.014", "Pemasangan Pipa Scaffolding Steel Penyangga Tegak Kolom", "set", "AHSP PUPR", "STRUKTUR_ATAS"),
        ("wi-kolom-cor-lt1", "STR.015", "Pengecoran Beton Kolom Utama Lantai 1 Mutu K-300", "m³", "SNI 2847", "STRUKTUR_ATAS"),
        ("wi-kolom-bongkar-bekisting", "STR.016", "Pembongkaran Bekisting Kolom Utama Setelah Beton Mengeras", "m²", "AHSP PUPR", "STRUKTUR_ATAS"),
        ("wi-kolom-curing-karung", "STR.017", "Pemasangan Lembaran Karung Goni Basah Keliling Kolom Utama", "m'", "SNI 2847", "STRUKTUR_ATAS"),
        ("wi-scaffolding-balok-lt2", "STR.018", "Pemasangan Perancah (Scaffolding) Besi Penuh untuk Balok Lantai 2", "m³", "AHSP PUPR", "STRUKTUR_ATAS"),
        ("wi-uhead-jack", "STR.019", "Pemasangan Struktur U-Head Jack & Jack Base Scaffolding", "set", "AHSP PUPR", "STRUKTUR_ATAS"),
        ("wi-suri-suri", "STR.020", "Pemasangan Balok Kayu Suri-Suri di Atas U-Head Scaffolding", "m'", "AHSP PUPR", "STRUKTUR_ATAS"),
        ("wi-bekisting-plat-lt2", "STR.021", "Pemasangan Bekisting Dasar Piringan Plat Lantai 2", "m²", "AHSP PUPR", "STRUKTUR_ATAS"),
        ("wi-bekisting-balok-lt2", "STR.022", "Pemasangan Bekisting Dinding Samping Balok Struktur Lantai 2", "m²", "AHSP PUPR", "STRUKTUR_ATAS"),
        ("wi-balok-lt2-rebar", "STR.023", "Fabrikasi Tulangan Besi Utama Balok Gantung Lantai 2", "kg", "SNI 2847", "STRUKTUR_ATAS"),
        ("wi-plat-lt2-wiremesh", "STR.024", "Perakitan Anyaman Besi Plat Lantai 2 Model 2 Lapis (D10)", "kg", "SNI 2847", "STRUKTUR_ATAS"),
        ("wi-plat-lt2-paku", "STR.025", "Pemasangan Paku Pengunci & Kawat Bendrat Anyaman Plat Lantai", "m²", "AHSP PUPR", "STRUKTUR_ATAS"),
        ("wi-sparing-kabel-lt2", "STR.026", "Penanaman Pipa Sparing Kabel Listrik Tembus Plat Lantai 2", "titik", "AHSP PUPR", "STRUKTUR_ATAS"),
        ("wi-sparing-airkotor-lt2", "STR.027", "Penanaman Pipa Sparing Air Kotor Kamar Mandi Tembus Plat Lantai", "titik", "AHSP PUPR", "STRUKTUR_ATAS"),
        ("wi-bersih-bekisting", "STR.028", "Pekerjaan Pembersihan Sampah Serbuk Kayu di Dalam Bekisting Balok", "m²", "AHSP PUPR", "STRUKTUR_ATAS"),
        ("wi-cor-massal-lt2", "STR.029", "Pengecoran Massal Balok & Plat Lantai 2 Paku Concrete Pump Truck", "m³", "SNI 2847", "STRUKTUR_ATAS"),
        ("wi-ratakan-cor-plat", "STR.030", "Perataan Permukaan Cor Beton Plat Lantai Paku Jidar Aluminium", "m²", "AHSP PUPR", "STRUKTUR_ATAS"),
        ("wi-curing-plat-lt2", "STR.031", "Perawatan Beton Plat Lantai 2 dengan Metode Penggenangan Air", "m²", "SNI 2847", "STRUKTUR_ATAS"),
        ("wi-bongkar-scaffolding-lt2", "STR.032", "Pembongkaran Perancah Scaffolding Balok Setelah Berusia 21 Hari", "m³", "AHSP PUPR", "STRUKTUR_ATAS"),
        ("wi-kolom-lt2-rebar", "STR.033", "Fabrikasi Besi Tulangan Kolom Utama Struktur Lantai 2", "kg", "SNI 2847", "STRUKTUR_ATAS"),
        ("wi-kolom-lt2-cor", "STR.034", "Pemasangan Bekisting & Pengecoran Kolom Utama Lantai 2 K-300", "m³", "SNI 2847", "STRUKTUR_ATAS"),
        ("wi-scaffolding-ringbalk", "STR.035", "Pemasangan Scaffolding Penyangga Balok Atap / Ring Balk", "m³", "AHSP PUPR", "STRUKTUR_ATAS"),
        ("wi-ringbalk-rebar", "STR.036", "Fabrikasi Besi & Pemasangan Bekisting Balok Atap (Ring Balk)", "kg", "SNI 2847", "STRUKTUR_ATAS"),
        ("wi-ringbalk-cor", "STR.037", "Pengecoran Beton Balok Atap (Ring Balk) Mutu K-225", "m³", "SNI 2847", "STRUKTUR_ATAS"),
        ("wi-dak-rebar", "STR.038", "Fabrikasi Besi Tulangan untuk Plat Dak Beton Atap Terbuka", "kg", "SNI 2847", "STRUKTUR_ATAS"),
        ("wi-roofdrain", "STR.039", "Pemasangan Pipa Drainase Air Hujan (Roof Drain) Tembus Dak", "titik", "AHSP PUPR", "STRUKTUR_ATAS"),
        ("wi-dak-cor", "STR.040", "Pengecoran Plat Dak Beton Atap Mutu K-250 Sistem Waterproof Admixture", "m³", "SNI 2847", "STRUKTUR_ATAS"),
        ("wi-tangga-bekisting", "STR.041", "Fabrikasi Besi & Bekisting Cetakan Tangga Beton Lantai 1 ke 2", "m²", "AHSP PUPR", "STRUKTUR_ATAS"),
        ("wi-tangga-rebar", "STR.042", "Perakitan Besi Tulangan Trap Anak Tangga Beton", "kg", "SNI 2847", "STRUKTUR_ATAS"),
        ("wi-tangga-cor", "STR.043", "Pengecoran Beton Tangga Bersamaan dengan Plat Lantai 2", "m³", "SNI 2847", "STRUKTUR_ATAS"),
        ("wi-kolom-praktis-rebar", "STR.044", "Fabrikasi Besi Tulangan Kolom Praktis 10x10 cm untuk Dinding", "kg", "SNI 2847", "STRUKTUR_ATAS"),
        ("wi-balok-lintel-rebar", "STR.045", "Perakitan Besi Balok Lintel / Balok Pengikat Kusen", "kg", "SNI 2847", "STRUKTUR_ATAS"),
        ("wi-kolom-praktis-cor", "STR.046", "Pengecoran Manual Kolom Praktis Campuran Site-Mix 1:2:3", "m³", "AHSP PUPR", "STRUKTUR_ATAS"),
        ("wi-angkur-dinding", "STR.047", "Pemasangan Besi Angkur Pengikat Dinding Bata ke Kolom Utama", "titik", "AHSP PUPR", "STRUKTUR_ATAS"),
        ("wi-konsol-kanopi", "STR.048", "Pekerjaan Dudukan Beton Konsol Kanopi Depan Rumah", "unit", "SNI 2847", "STRUKTUR_ATAS"),
        ("wi-meja-dapur-cor", "STR.049", "Pekerjaan Beton Meja Dapur (Kitchen Table) Cor di Tempat", "unit", "SNI 2847", "STRUKTUR_ATAS"),
    ]
    for args in items:
        kg.add_work_item(WorkItemNode(*args))
    print(f"  ✅ Struktur Atas: {len(items)} item pekerjaan dimuat")
