"""initial digital twin tables

Revision ID: 3f3264212a74
Revises: 
Create Date: 2026-08-24 17:41:04.614209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f3264212a74'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archive_records',
    sa.Column('archive_uuid', sa.String(), nullable=False),
    sa.Column('project_uuid', sa.String(), nullable=False),
    sa.Column('archived_at', sa.String(), nullable=False),
    sa.Column('project_metadata', sa.Text(), nullable=True),
    sa.Column('snapshots', sa.Text(), nullable=True),
    sa.Column('as_built_records', sa.Text(), nullable=True),
    sa.Column('audit_events', sa.Text(), nullable=True),
    sa.Column('extra_metadata', sa.Text(), nullable=True),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('archive_uuid')
    )
    op.create_index(op.f('ix_archive_records_project_uuid'), 'archive_records', ['project_uuid'], unique=False)
    op.create_table('as_built_records',
    sa.Column('record_uuid', sa.String(), nullable=False),
    sa.Column('project_uuid', sa.String(), nullable=False),
    sa.Column('entity_uuid', sa.String(), nullable=False),
    sa.Column('planned_state', sa.Text(), nullable=True),
    sa.Column('as_built_state', sa.Text(), nullable=True),
    sa.Column('differences', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('record_uuid')
    )
    op.create_index(op.f('ix_as_built_records_project_uuid'), 'as_built_records', ['project_uuid'], unique=False)
    op.create_table('audit_events',
    sa.Column('event_uuid', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('actor', sa.Text(), nullable=False),
    sa.Column('target', sa.Text(), nullable=False),
    sa.Column('change_detail', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('related_vo', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('extra_metadata', sa.Text(), nullable=True),
    sa.Column('prev_hash', sa.String(), nullable=True),
    sa.Column('hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('event_uuid')
    )
    op.create_index(op.f('ix_audit_events_timestamp'), 'audit_events', ['timestamp'], unique=False)
    op.create_table('change_orders',
    sa.Column('vo_uuid', sa.String(), nullable=False),
    sa.Column('project_uuid', sa.String(), nullable=False),
    sa.Column('vo_number', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('request_date', sa.String(), nullable=False),
    sa.Column('requested_by', sa.String(), nullable=True),
    sa.Column('ccm_changes', sa.Text(), nullable=True),
    sa.Column('boq_impact', sa.Text(), nullable=True),
    sa.Column('cost_impact', sa.Text(), nullable=True),
    sa.Column('schedule_impact', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('approval_chain', sa.Text(), nullable=True),
    sa.Column('baseline_before', sa.String(), nullable=True),
    sa.Column('baseline_after', sa.String(), nullable=True),
    sa.Column('extra_metadata', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('vo_uuid')
    )
    op.create_index(op.f('ix_change_orders_project_uuid'), 'change_orders', ['project_uuid'], unique=False)
    op.create_table('progress_entries',
    sa.Column('progress_entry_uuid', sa.String(), nullable=False),
    sa.Column('project_uuid', sa.String(), nullable=False),
    sa.Column('report_date', sa.String(), nullable=False),
    sa.Column('report_type', sa.String(), nullable=False),
    sa.Column('period_start', sa.String(), nullable=True),
    sa.Column('period_end', sa.String(), nullable=True),
    sa.Column('overall_progress_percentage', sa.Float(), nullable=True),
    sa.Column('entity_progress', sa.Text(), nullable=True),
    sa.Column('issues', sa.Text(), nullable=True),
    sa.Column('weather', sa.Text(), nullable=True),
    sa.Column('labor_on_site', sa.Text(), nullable=True),
    sa.Column('material_delivered', sa.Text(), nullable=True),
    sa.Column('extra_metadata', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('progress_entry_uuid')
    )
    op.create_index(op.f('ix_progress_entries_project_uuid'), 'progress_entries', ['project_uuid'], unique=False)
    op.create_table('snapshots',
    sa.Column('snapshot_uuid', sa.String(), nullable=False),
    sa.Column('snapshot_name', sa.String(), nullable=False),
    sa.Column('snapshot_type', sa.String(), nullable=False),
    sa.Column('project_uuid', sa.String(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ccm_state', sa.Text(), nullable=False),
    sa.Column('boq_state', sa.Text(), nullable=True),
    sa.Column('rab_state', sa.Text(), nullable=True),
    sa.Column('schedule_state', sa.Text(), nullable=True),
    sa.Column('extra_metadata', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('snapshot_uuid')
    )
    op.create_index(op.f('ix_snapshots_project_uuid'), 'snapshots', ['project_uuid'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('extra_metadata', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_index(op.f('ix_snapshots_project_uuid'), table_name='snapshots')
    op.drop_table('snapshots')
    op.drop_index(op.f('ix_progress_entries_project_uuid'), table_name='progress_entries')
    op.drop_table('progress_entries')
    op.drop_index(op.f('ix_change_orders_project_uuid'), table_name='change_orders')
    op.drop_table('change_orders')
    op.drop_index(op.f('ix_audit_events_timestamp'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_as_built_records_project_uuid'), table_name='as_built_records')
    op.drop_table('as_built_records')
    op.drop_index(op.f('ix_archive_records_project_uuid'), table_name='archive_records')
    op.drop_table('archive_records')
    # ### end Alembic commands ###
