# fastra_core\knowledge\domains\labor\auto_generated.py

from __future__ import annotations

import logging
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, ConfigDict, Field

from fastra_core.knowledge.graph import KnowledgeGraph
from fastra_core.knowledge.nodes import LaborNode, NodeLaborRole

logger = logging.getLogger("fastra.knowledge")


# ---------------------------------------------------------------------------
# Inbound DTOs – Pydantic Strict Gateway & Sanitization (Fail-Fast)
# ---------------------------------------------------------------------------
class AutoGeneratedLaborItemDTO(BaseModel):
    """DTO validasi ketat untuk mendaftar data upah cetakan generator otomatis."""
    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True, strict=True)

    id: str = Field(..., min_length=5, max_length=64, pattern=r"^lab_[a-z0-9_]+$")
    name: str = Field(..., min_length=2, max_length=256)
    role: NodeLaborRole = Field(...)
    daily_rate: float = Field(..., ge=0.0, le=1e11, allow_inf_nan=False)
    region: str = Field(default="", max_length=64)


class AutoGeneratedLaborBundleDTO(BaseModel):
    """Bundel manifes penampung sekumpulan daftar upah generator otomatis."""
    model_config = ConfigDict(extra="forbid", strict=True)
    items: List[AutoGeneratedLaborItemDTO] = Field(default_factory=list, max_length=1000)


# ---------------------------------------------------------------------------
# Core Utilities & Automated Seeding Generator Layer
# ---------------------------------------------------------------------------
def load_labor_auto_generated(kg: KnowledgeGraph) -> None:
    """
    Memuat dan menginjeksikan data repositori upah harian Orang Hari (OH) dinamis.
    Menghilangkan celah bypass tipe data ilegal dengan pengunci skema batiniah node.
    """
    if not isinstance(kg, KnowledgeGraph):
        raise TypeError("Parameter masukan 'kg' wajib berupa instance orisinil dari kelas KnowledgeGraph.")

    # Kumpulan data benih upah harian terstandarisasi regional (AHS Kementerian PUPR)
    raw_bundle_payload: List[Dict[str, Any]] = [
        {
            "id": "lab_pekerja",
            "name": "Pekerja Lapangan Umum",
            "role": "PEKERJA",
            "daily_rate": 120000.0,
            "region": "DKI JAKARTA"
        },
        {
            "id": "lab_tukang_batu",
            "name": "Tukang Batu Terampil",
            "role": "TUKANG",
            "daily_rate": 150000.0,
            "region": "DKI JAKARTA"
        },
        {
            "id": "lab_kepala_tukang",
            "name": "Kepala Tukang Struktur",
            "role": "KEPALA_TUKANG",
            "daily_rate": 165000.0,
            "region": "DKI JAKARTA"
        },
        {
            "id": "lab_mandor",
            "name": "Mandor / Pengawas Konstruksi",
            "role": "MANDOR",
            "daily_rate": 180000.0,
            "region": "DKI JAKARTA"
        }
    ]

    # 1. GATEWAY SCHEMA VALIDATION: Penyaringan fail-fast terpusat
    try:
        validated_bundle = AutoGeneratedLaborBundleDTO(items=raw_bundle_payload)
    except Exception as exc:
        logger.error(f"Gagal memuat benih upah otomatis: Kegagalan skema data: {str(exc)}")
        return

    # 2. INMUTABLE OBJECT CONSTRUCTOR MAPPING PIPELINE
    for item_dto in validated_bundle.items:
        # Instansiasi objek dipaksa melalui kelas murni LaborNode yang aman secara aritmatika desimal
        labor_instance = LaborNode(
            id=item_dto.id,
            name=item_dto.name,
            role=item_dto.role,
            daily_rate=item_dto.daily_rate,
            region=item_dto.region
        )
        kg.add_labor(labor_instance)

    logger.info(
        "Daftar upah otomatis sukses disuntikkan ke repositori utama: %d entri Orang Hari dikunci.", 
        len(validated_bundle.items)
    )